name: JRuby Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec-jruby:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/jruby.gemfile

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: jruby
    - name: Install Ruby deps
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec
